development:
  adapter: postgresql
  encoding: unicode
  database: rubr_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rubr_test
  pool: 5
  username:
  password:

